---

- hosts: all 
  name: Install Docker  
  remote_user: ci
  become: yes
  tasks: 
  - name: Install packages to allow apt to use a repository over HTTPS
    apt: 
      name: 
        - ca-certificates
        - gnupg
        - apt-transport-https
      # Install and skip if the packages exists before
      state: present 
      # sudo apt update first :)
      update_cache: yes

  - name: Add Docker’s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Get Ubuntu release version
    shell: lsb_release -cs
    register: ubuntu_version

  - name: Get architecture
    shell: dpkg --print-architecture
    register: architecture

  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
      state: present
      filename: docker

  - name: Update apt packages
    apt:
      update_cache: "yes"

  - name: Install Docker engine
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes

  # Allow user using docker commands without using sudo
  - name: Add current user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
    # Using sudo command when add user to docker group
    become: yes
